global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']

  - job_name: 'service-a'
    static_configs:
      - targets: ['service-a:8080']

  - job_name: 'service-b'
    static_configs:
      - targets: ['service-b:8080']